resources:
  - https://github.com/prometheus-operator/kube-prometheus.git?ref=v0.10.0
  - prometheus-clusterrole.yaml
  - prometheus-clusterrolebinding.yaml.yaml
  - grafana-ingress.yaml
  - prom-ingress.yaml
