apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bind
commonLabels:
  app: bind
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: named-conf
    files:
      - named.conf
  - name: loutretelecomzone
    files:
      - db.loutretele.com
