apiVersion: v1
kind: Service
metadata:
  name: bind
spec:
  ports:
    - name: udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: tcp
      port: 53
      targetPort: 53
      protocol: TCP
