apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  creationTimestamp: null
  name: k0s
spec:
  api:
    address: 10.72.18.9
    k0sApiPort: 9443
    port: 6443
    sans:
    - 10.72.18.9
    - 10.244.0.1
    - 2001:bc8:650:904::1
    - fe80::dc1c:7cff:fe12:e005
    - fe80::44fd:87ff:feed:d924
    - fe80::482e:bfff:fe54:80bd
    - fe80::389b:5bff:fef9:8b99
    - fe80::8c60:3bff:fe4a:c77d
    - fe80::34df:e6ff:fe31:3a04
    - fe80::502d:e1ff:fe74:73e3
    - fe80::b0a0:8bff:fe15:8f83
    - fe80::2c7e:c0ff:fedc:e0c0
    - fe80::e868:16ff:fec5:6ab9
    tunneledNetworkingMode: false
  controllerManager: {}
  extensions:
    helm:
      charts: null
      repositories: null
    storage:
      create_default_storage_class: false
      type: external_storage
  images:
    calico:
      cni:
        image: docker.io/calico/cni
        version: v3.21.2
      kubecontrollers:
        image: docker.io/calico/kube-controllers
        version: v3.21.2
      node:
        image: docker.io/calico/node
        version: v3.21.2
    coredns:
      image: k8s.gcr.io/coredns/coredns
      version: v1.7.0
    default_pull_policy: IfNotPresent
    konnectivity:
      image: quay.io/k0sproject/apiserver-network-proxy-agent
      version: 0.0.27-k0s1
    kubeproxy:
      image: k8s.gcr.io/kube-proxy
      version: v1.23.1
    kuberouter:
      cni:
        image: docker.io/cloudnativelabs/kube-router
        version: v1.3.2
      cniInstaller:
        image: quay.io/k0sproject/cni-node
        version: 0.1.0
    metricsserver:
      image: k8s.gcr.io/metrics-server/metrics-server
      version: v0.5.0
  installConfig:
    users:
      etcdUser: etcd
      kineUser: kube-apiserver
      konnectivityUser: konnectivity-server
      kubeAPIserverUser: kube-apiserver
      kubeSchedulerUser: kube-scheduler
  konnectivity:
    adminPort: 8133
    agentPort: 8132
  network:
    calico:
      mode: bird
    dualStack:
      enabled: true
      IPv6podCIDR: "fd00::/108"
      IPv6serviceCIDR: "fd01::/108"
    podCIDR: 10.244.0.0/16
    provider: calico
    serviceCIDR: 10.96.0.0/12
  podSecurityPolicy:
    defaultPolicy: 00-k0s-privileged
  scheduler: {}
  storage:
    etcd:
      peerAddress: 10.72.18.9
    type: etcd
  telemetry:
    enabled: true
status: {}
