namespace: argocd
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.2.3/manifests/install.yaml
  - https://raw.githubusercontent.com/argoproj-labs/applicationset/v0.3.0/manifests/install.yaml
patchesStrategicMerge:
  - argocd_svc_loadbalancer.yaml
