namespace: argocd
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.2.3/manifests/install.yaml
  - https://raw.githubusercontent.com/argoproj-labs/applicationset/v0.3.0/manifests/install.yaml
  - ingresses.yaml

configMapGenerator:
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
      - server.insecure="true"
  - name: argocd-cm
    behavior: merge
    literals:
      - application.instanceLabelKey="argocd.argoproj.io/instance"
